### ISSUE TITLE
bundle deps ?

### ISSUE THREAD

**Issue by jbenet** [active9/screencap#1]
would be very nice to bundle the deps. see https://github.com/mafintosh/playback/ for how to npm install a bunch of hard things (like ffmpeg, i think)

**Comment by active9** [comment]
This is actually a non issue since the core installs Ffmpeg via fluent-ffmpeg per system. The other prerequisites have their own installers so bundling them isn't really an option. Manually installing FFMPEG may not be required on some systems (Such as Windows).
