### ISSUE TITLE
how to record full screen desktop?

### ISSUE THREAD

**Issue by esraldi** [active9/screencap#2]
how to record full screen desktop? i'm used windows. it's work but not full screen.

**Comment by talkquazi** [comment]
As seen here https://github.com/rdp/screen-capture-recorder-to-video-windows-free#configuration the answer to your question is. By default it records the entire screen.

Here is the excerpt from that page:

By default, it captures the "full screen" of the main desktop monitor (all windows, overlapping, from there, with aero if vista+, without transparent windows if non aero).

To configure it differently, run the provided "configuration setup utilities/shortcuts" or adjust registry settings before starting a run (advanced users only):

HKEY_CURRENT_USER\Software\screen-capture-recorder

with DWORD keys respected of start_XXX etc …​ (see the included file {installdir}\configuration_setup_utility\setup_screen_tracker_params.rb for the full list of registry key values available, or see https://github.com/rdp/screen-capture-recorder-to-video-windows-free/blob/master/configuration_setup_utility/setup_screen_tracker_params.rb#L9 )

ex: see configuration_setup_utility\incoming.reg file (though NB that those values are in hex, so editing that file is a bit tedious-- I always just use regedit or the accompanying script utilities and don’t edit it by hand).

To "reset" a value delete its key.
